### ISSUE TITLE
Setting up Sim for Piano Hand

### ISSUE THREAD

**Issue by revanthsenthil** [purdue-arc/arc-piano-hand#11]
Finding a suitable simulation environment and deploying models onto simulation for testing.

**Comment by revanthsenthil** [comment]
Using Unity for Sim

**Comment by revanthsenthil** [comment]
Currently setting up and understanding webots for all members

**Comment by NarenR21** [comment]
Goals and Timeline for Sim: (Individual task will be detailed below.)

Feb 11th finalize familiarity and training.
Feb 18th able to read a force sensor on the fingertip
Mar 2nd simple algorithm
